apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  source:
    helm:
      values: |
        # Dev environment - smaller resources
        prometheus:
          prometheusSpec:
            retention: 7d
            retentionSize: 5GB
            resources:
              limits:
                cpu: 200m
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 512Mi
            storageSpec:
              volumeClaimTemplate:
                spec:
                  resources:
                    requests:
                      storage: 10Gi
        
        grafana:
          persistence:
            size: 5Gi
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
        
        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  resources:
                    requests:
                      storage: 5Gi
            resources:
              limits:
                cpu: 100m
                memory: 256Mi
              requests:
                cpu: 50m
                memory: 128Mi 