version: '3.8'

services:
  eks-manager:
    build: .
    container_name: eks-cluster-manager
    working_dir: /eks-cluster
    environment:
      - AWS_REGION=${AWS_REGION:-ap-southeast-2}
      - CLUSTER_NAME=${CLUSTER_NAME:-production-eks}
      - AWS_PROFILE=${AWS_PROFILE:-default}
    volumes:
      # AWS credentials and config
      - ~/.aws:/root/.aws:ro
      # Kubernetes config
      - ~/.kube:/root/.kube
      # Current project directory
      - .:/eks-cluster
      # Docker socket for building images if needed
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    networks:
      - eks-network

  # Optional: AWS LocalStack for testing
  localstack:
    image: localstack/localstack:latest
    container_name: eks-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ec2,iam,sts,cloudformation,eks
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack-data:/tmp/localstack/data
    networks:
      - eks-network
    profiles:
      - testing

networks:
  eks-network:
    driver: bridge 