apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base applications
resources:
  - ../../applications/aws-load-balancer-controller.yaml
  - ../../applications/cluster-autoscaler.yaml
  - ../../applications/monitoring.yaml
  - ../../applications/ingress-nginx.yaml
  - ../../applications/external-dns.yaml
  - ../../applications/cert-manager.yaml

# Environment-specific patches
patchesStrategicMerge:
  - patches/cluster-autoscaler-patch.yaml
  - patches/monitoring-patch.yaml

# Namespace transformations
namespace: argocd

# Common labels for staging environment
commonLabels:
  environment: staging
  managed-by: argocd 