apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  labels:
    app.kubernetes.io/name: cluster-autoscaler
    app.kubernetes.io/component: autoscaling
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/autoscaler
    chart: cluster-autoscaler
    targetRevision: 9.29.0
    helm:
      releaseName: cluster-autoscaler
      values: |
        autoDiscovery:
          clusterName: production-cluster  # Update with your cluster name
        
        awsRegion: ap-southeast-2
        
        serviceAccount:
          create: true
          name: cluster-autoscaler
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::YOUR_ACCOUNT:role/AmazonEKSClusterAutoscalerRole
        
        rbac:
          create: true
          serviceAccount:
            name: cluster-autoscaler
        
        image:
          repository: k8s.gcr.io/autoscaling/cluster-autoscaler
          tag: v1.27.3
        
        replicaCount: 2
        
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
        
        nodeSelector:
          kubernetes.io/arch: amd64
        
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
        
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - cluster-autoscaler
                topologyKey: kubernetes.io/hostname
        
        extraArgs:
          logtostderr: true
          stderrthreshold: info
          v: 4
          skip-nodes-with-local-storage: false
          expander: least-waste
          node-group-auto-discovery: asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/production-cluster
          balance-similar-node-groups: false
          skip-nodes-with-system-pods: false
          scale-down-enabled: true
          scale-down-delay-after-add: 10m
          scale-down-delay-after-delete: 10s
          scale-down-delay-after-failure: 3m
          scale-down-unneeded-time: 10m
          scale-down-utilization-threshold: 0.5
          max-node-provision-time: 15m
        
        podDisruptionBudget:
          maxUnavailable: 1
        
        serviceMonitor:
          enabled: true
          namespace: kube-system
          interval: 30s
          path: /metrics
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 