apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base applications - production uses them as-is
resources:
  - ../../applications/aws-load-balancer-controller.yaml
  - ../../applications/cluster-autoscaler.yaml
  - ../../applications/monitoring.yaml
  - ../../applications/ingress-nginx.yaml
  - ../../applications/external-dns.yaml
  - ../../applications/cert-manager.yaml

# Namespace transformations
namespace: argocd

# Common labels for production environment
commonLabels:
  environment: production
  managed-by: argocd 